#基础信息
title: winmay的博客
email: 404348894@qq.com
url: Winmay.github.io
avatar: http://image.fishedee.com/1.pic.jpg
description: 一个安静的女程序猿

#文档配置
markdown: kramdown
kramdown:
  input: GFM
  extensions:
    - autolink
    - footnotes
    - smart
  enable_coderay: true
  syntax_highlighter: rouge
  coderay:
    coderay_line_numbers:  nil

#评论配置
disqus: 

#统计配置
baidu: 


